// Emits CREDITS.md from src/effects/catalog.ts. Scans the catalog as text so it
// has zero runtime dependencies (the catalog imports only types). Lists every
// effect that carries a `credit` or an attribution license (the two BSD shaders,
// all credited gl-transitions authors, etc.). Run: `npm run credits`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(join(root, "src/effects/catalog.ts"), "utf8");

const INFORMAL = new Set(["MIT", "write-own", "technique", "asset", "simulated"]);
const field = (line, key) => {
  const m = line.match(new RegExp(`${key}:\\s*"([^"]*)"`));
  return m ? m[1] : undefined;
};

const entries = src
  .split("\n")
  .filter((l) => /\bid:\s*"/.test(l))
  .map((l) => ({
    id: field(l, "id"),
    name: field(l, "name"),
    license: field(l, "license"),
    credit: field(l, "credit"),
  }))
  .filter((e) => e.id && (e.credit || (e.license && !INFORMAL.has(e.license))));

const body = entries
  .map((e) => `- **${e.name}** (\`${e.id}\`) — ${e.license ?? "MIT"}${e.credit ? ` — ${e.credit}` : ""}`)
  .join("\n");

const md = `# Credits & Licenses

> Generated by \`npm run credits\` from \`src/effects/catalog.ts\`. These effect
> sources require attribution when their shader/source code is shipped. Rendered
> video output itself carries no practical restriction.

${body}
`;

writeFileSync(join(root, "CREDITS.md"), md);
console.log(`Wrote CREDITS.md (${entries.length} attributed entries).`);
